# Generated by Django 5.2 on 2025-06-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosBancarios',
        ),
    ]
