# Generated by Django 5.2.1 on 2025-05-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='primeiro_acesso',
            field=models.BooleanField(default=False, verbose_name='Primeiro Acesso'),
        ),
    ]
