# Generated by Django 5.2 on 2025-05-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='objetivos',
        ),
    ]
