# Generated by Django 5.2 on 2025-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='total_faltas',
            field=models.IntegerField(default=0, verbose_name='total_faltas'),
        ),
    ]
