# Generated by Django 5.2 on 2025-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professores',
            name='primeiro_acesso',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Primeiro Acesso'),
        ),
    ]
