# Generated by Django 5.2 on 2025-05-16 17:15

import preLogin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='primeiro_acesso',
            field=models.BooleanField(default=False, verbose_name='Primeiro Acesso'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, validators=[preLogin.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='coordenadores',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[preLogin.validators.validar_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='professores',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[preLogin.validators.validar_cpf], verbose_name='CPF'),
        ),
    ]
