# Generated by Django 5.2 on 2025-06-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provas',
            name='turma',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='preLogin.turmas', verbose_name='Turma'),
            preserve_default=False,
        ),
    ]
