# Generated by Django 5.2 on 2025-05-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0002_professores_primeiro_acesso_alter_alunos_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='id_inscricao',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Inscrição'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
