# Generated by Django 5.2 on 2025-06-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0002_frequencia_total_faltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='presenca',
        ),
    ]
