# Generated by Django 5.2 on 2025-06-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0002_provas_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='provas',
            name='etapa',
            field=models.CharField(default='nada', verbose_name='Etapa'),
            preserve_default=False,
        ),
    ]
