# Generated by Django 5.2 on 2025-05-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0002_remove_aulas_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preLogin.turmas', verbose_name='Turma'),
        ),
    ]
