# Generated by Django 5.2 on 2025-05-28 12:29

import django.db.models.deletion
import preLogin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0003_professores_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professores',
            name='turma',
        ),
        migrations.AddField(
            model_name='turmas',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preLogin.professores', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='coordenadores',
            name='rg',
            field=models.CharField(max_length=11, unique=True, validators=[preLogin.validators.validar_rg], verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='professores',
            name='rg',
            field=models.CharField(max_length=11, unique=True, validators=[preLogin.validators.validar_rg], verbose_name='RG'),
        ),
    ]
