# Generated by Django 5.2 on 2025-06-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0003_remove_frequencia_presenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='aula',
        ),
    ]
