# Generated by Django 5.2 on 2025-06-15 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0004_remove_frequencia_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='aula',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='preLogin.aulas', verbose_name='Aula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequencia',
            name='falta',
            field=models.BooleanField(default=False, verbose_name='falta'),
        ),
    ]
