# Generated by Django 5.2 on 2025-05-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0004_remove_professores_turma_turmas_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='semestre_letivo',
        ),
        migrations.AddField(
            model_name='turmas',
            name='semestre_atual',
            field=models.CharField(default=1, max_length=6, verbose_name='Semestre atual'),
        ),
        migrations.AddField(
            model_name='turmas',
            name='semestre_turma',
            field=models.CharField(default=1, max_length=1, verbose_name='Semestre da turma'),
        ),
    ]
