# Generated by Django 5.2 on 2025-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0005_remove_turmas_semestre_letivo_turmas_semestre_atual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='semestre_atual',
            field=models.CharField(max_length=6, verbose_name='Semestre atual'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='semestre_turma',
            field=models.CharField(max_length=1, verbose_name='Semestre da turma'),
        ),
    ]
