# Generated by Django 5.2 on 2025-06-15 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0005_frequencia_aula_frequencia_falta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='total_faltas',
        ),
    ]
