# Generated by Django 5.2 on 2025-05-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0006_alter_turmas_semestre_atual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turmas',
            old_name='semestre_turma',
            new_name='semestre_letivo',
        ),
    ]
