# Generated by Django 5.2 on 2025-05-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0007_rename_semestre_turma_turmas_semestre_letivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmas',
            name='semestre_atual',
        ),
    ]
