# Generated by Django 5.2 on 2025-05-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0008_remove_turmas_semestre_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='semestre_atual',
            field=models.CharField(default=1, max_length=6, verbose_name='Semestre atual'),
            preserve_default=False,
        ),
    ]
