# Generated by Django 5.2 on 2025-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0009_turmas_semestre_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='objetivos',
            field=models.TextField(default='teste', verbose_name='Objetivos'),
            preserve_default=False,
        ),
    ]
