# Generated by Django 5.2 on 2025-05-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0010_aulas_objetivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='numero_turma',
            field=models.CharField(default=1, max_length=1, verbose_name='Numero da turma'),
            preserve_default=False,
        ),
    ]
