# Generated by Django 5.2.2 on 2025-06-07 14:56

import django.core.validators
import django.db.models.deletion
import preLogin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='preLogin.professores', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='confirmacao_egresso',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Pedido de rematrícula'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='situacao',
            field=models.CharField(choices=[('Cursando', 'Cursando'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=255, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='objetivos',
            field=models.TextField(verbose_name='Objetivos'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='como_conheceu',
            field=models.CharField(choices=[('Rede_Social', 'Rede Social'), ('Indicação', 'Indicação'), ('TV', 'TV'), ('Outro', 'Outro')], max_length=20, verbose_name='Como conheceu o Eclass'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='diploma_ensino_medio',
            field=models.FileField(upload_to=preLogin.models.upload_path, verbose_name='Diploma Ensino Médio'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='foto_frente',
            field=models.FileField(upload_to=preLogin.models.upload_path, verbose_name='Foto identidade - frente'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='foto_verso',
            field=models.FileField(upload_to=preLogin.models.upload_path, verbose_name='Foto identidade - verso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='motivacao',
            field=models.TextField(verbose_name='Motivação para o curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='ocupacao',
            field=models.CharField(max_length=255, verbose_name='Ocupação atual'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='qual_deficiencia',
            field=models.CharField(blank=True, choices=[('Física', 'Física'), ('Auditiva', 'Auditiva'), ('Visual', 'Visual'), ('Intelectual', 'Intelectual'), ('Múltipla', 'Múltipla'), ('Outra', 'Outra')], null=True, verbose_name='Tipo de deficiência'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='termo_inscricao',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=5, verbose_name='Termo de inscrição'),
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id_diario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_Diario')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da aula')),
                ('objetivos', models.TextField(verbose_name='Objetivos da aula')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preLogin.turmas', verbose_name='Turma')),
            ],
            options={
                'verbose_name_plural': 'Diários',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='professores',
            name='diarios',
            field=models.ManyToManyField(blank=True, to='preLogin.diario', verbose_name='Diários'),
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('participacao', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Participação')),
                ('tarefa', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Tarefa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do aluno')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preLogin.alunos', verbose_name='Aluno')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preLogin.diario', verbose_name='Diário')),
            ],
            options={
                'verbose_name_plural': 'Registros Diários',
                'unique_together': {('diario', 'aluno')},
            },
        ),
        migrations.DeleteModel(
            name='DadosBancarios',
        ),
    ]
