# Generated by Django 5.2.2 on 2025-06-07 15:04

import preLogin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0002_turmas_professor_alter_alunos_confirmacao_egresso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadores',
            name='rg',
            field=models.CharField(max_length=12, unique=True, validators=[preLogin.validators.validar_rg], verbose_name='RG'),
        ),
    ]
