# Generated by Django 5.2.2 on 2025-06-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0003_alter_coordenadores_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenadores',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='coordenadores',
            name='rg',
            field=models.CharField(max_length=12, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='coordenadores',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
    ]
