# Generated by Django 5.2.2 on 2025-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0004_alter_coordenadores_cpf_alter_coordenadores_rg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='professores',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='professores',
            name='rg',
            field=models.CharField(max_length=9, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='professores',
            name='telefone',
            field=models.CharField(max_length=12, verbose_name='Telefone'),
        ),
    ]
