# Generated by Django 5.2.2 on 2025-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0005_alter_inscricao_cpf_alter_professores_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
    ]
