# Generated by Django 5.2.2 on 2025-06-07 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0006_alter_alunos_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preLogin.provas'),
        ),
    ]
