# Generated by Django 5.2.2 on 2025-06-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0007_registrodiario_prova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='prova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preLogin.alunosprovas'),
        ),
    ]
