# Generated by Django 5.2.2 on 2025-06-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preLogin', '0008_alter_registrodiario_prova'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodiario',
            name='participacao',
        ),
        migrations.RemoveField(
            model_name='registrodiario',
            name='tarefa',
        ),
    ]
