# Generated by Django 5.2 on 2025-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default="Sem Nome", max_length=255, null= True,)),
                ('lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
