# Generated by Django 5.2 on 2025-04-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
