# Generated by Django 5.2 on 2025-05-04 17:37

import testedb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexosinscricao',
            name='arquivo',
            field=models.FileField(upload_to=testedb.models.upload_path),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='diploma_ensino_medio',
            field=models.FileField(upload_to=testedb.models.upload_path, verbose_name='Foto do diploma do ensino médio'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='foto_frente',
            field=models.FileField(upload_to=testedb.models.upload_path, verbose_name='Foto da identidade (Frente)'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='foto_verso',
            field=models.FileField(upload_to=testedb.models.upload_path, verbose_name='Foto da identidade (Verso)'),
        ),
    ]
