# Generated by Django 5.2 on 2025-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='anexo',
            field=models.FileField(default='', upload_to='media/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='anexosinscricao',
            name='arquivo',
            field=models.FileField(upload_to='inscricoes/anexos/', verbose_name='Documentos'),
        ),
    ]
