# Generated by Django 5.2 on 2025-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testedb', '0002_inscricao_anexo_alter_anexosinscricao_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='anexo',
        ),
        migrations.AlterField(
            model_name='anexosinscricao',
            name='arquivo',
            field=models.FileField(upload_to='media/', verbose_name='Documentos'),
        ),
    ]
