# Generated by Django 5.2 on 2025-04-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testedb', '0002_alter_alunos_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
    ]
