# Generated by Django 5.2 on 2025-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testedb', '0003_alter_alunos_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('idade', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='firstname',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='alunos',
            old_name='lastname',
            new_name='sobrenome',
        ),
        migrations.AddField(
            model_name='alunos',
            name='idade',
            field=models.IntegerField(null=True),
        ),
    ]
