# Generated by Django 5.2 on 2025-05-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posLogin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aula',
        ),
    ]
