# Generated by Django 5.2 on 2025-05-06 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='alunosprovas',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='alunosprovas',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='anexosinscricao',
            name='inscricao',
        ),
        migrations.RemoveField(
            model_name='aulas',
            name='turma',
        ),
        migrations.DeleteModel(
            name='Coordenadores',
        ),
        migrations.RemoveField(
            model_name='dadosbancarios',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='aula',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Professores',
        ),
        migrations.DeleteModel(
            name='Provas',
        ),
        migrations.DeleteModel(
            name='Turmas',
        ),
        migrations.DeleteModel(
            name='Alunos',
        ),
        migrations.DeleteModel(
            name='AlunosProvas',
        ),
        migrations.DeleteModel(
            name='AnexosInscricao',
        ),
        migrations.DeleteModel(
            name='Aulas',
        ),
        migrations.DeleteModel(
            name='DadosBancarios',
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
